apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-a-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-a-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-a-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{  .Values.env.POD_NAMESPACE }}
roleRef:
  kind: Role
  name: service-a-role
  apiGroup: rbac.authorization.k8s.io
