apiVersion: v1
kind: Service
metadata:
  name: {{ include "wsc-exam.fullname" . }}
  labels:
    {{- include "wsc-exam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "wsc-exam.selectorLabels" . | nindent 4 }}
